class CategoryIcons {
  static const iconData = {
    //General
    1: 'assets/images/category_icons/food.svg',
    2: 'assets/images/category_icons/phone.svg',
    3: 'assets/images/category_icons/house.svg',
    4: 'assets/images/category_icons/entertainment.svg',
    5: 'assets/images/category_icons/education.svg',
    6: 'assets/images/category_icons/beauty.svg',
    7: 'assets/images/category_icons/sport.svg',
    8: 'assets/images/category_icons/transportation.svg',
    9: 'assets/images/category_icons/clothing.svg',
    10: 'assets/images/category_icons/car.svg',
    11: 'assets/images/category_icons/electronics.svg',
    12: 'assets/images/category_icons/travel.svg',
    13: 'assets/images/category_icons/health.svg',
    14: 'assets/images/category_icons/pet.svg',
    15: 'assets/images/category_icons/carrot.svg',
    16: 'assets/images/category_icons/pear.svg',
    17: 'assets/images/category_icons/credit-card.svg',
    18: 'assets/images/category_icons/money-plant.svg',
    19: 'assets/images/category_icons/clock-with-dollar-sign.svg',
    20: 'assets/images/category_icons/award.svg',
    21: 'assets/images/category_icons/other-income.svg',
    22: 'assets/images/category_icons/electricity.svg',

    //Entertainment
    23: 'assets/images/category_icons/game-controller.svg',
    24: 'assets/images/category_icons/ghost.svg',
    25: 'assets/images/category_icons/tennis-ball.svg',
    26: 'assets/images/category_icons/table-tennis.svg',
    27: 'assets/images/category_icons/board-games.svg',
    28: 'assets/images/category_icons/radio.svg',
    29: 'assets/images/category_icons/robot.svg',
    30: 'assets/images/category_icons/nintendo.svg',
    31: 'assets/images/category_icons/water-gun.svg',
    32: 'assets/images/category_icons/bowling.svg',
    33: 'assets/images/category_icons/skate.svg',

    //Food
    34: 'assets/images/category_icons/bread.svg',
    35: 'assets/images/category_icons/tea.svg',
    36: 'assets/images/category_icons/food.svg',
    37: 'assets/images/category_icons/candy.svg',
    38: 'assets/images/category_icons/aubergine.svg',
    39: 'assets/images/category_icons/dog-food.svg',
    40: 'assets/images/category_icons/chicken-leg.svg',
    41: 'assets/images/category_icons/fish.svg',
    42: 'assets/images/category_icons/noodles.svg',
    43: 'assets/images/category_icons/pizza.svg',
    44: 'assets/images/category_icons/cake.svg',
    45: 'assets/images/category_icons/icecream.svg',
    46: 'assets/images/category_icons/milk.svg',
    47: 'assets/images/category_icons/watermelon.svg',
    48: 'assets/images/category_icons/strawberry.svg',
    49: 'assets/images/category_icons/pineapple.svg',
    50: 'assets/images/category_icons/beer.svg',
    
    //Apparel
    51: 'assets/images/category_icons/bag.svg',
    52: 'assets/images/category_icons/hat.svg',
    53: 'assets/images/category_icons/jewelry.svg',
    54: 'assets/images/category_icons/shoe.svg',
    55: 'assets/images/category_icons/perfume.svg',
    56: 'assets/images/category_icons/shirt.svg',
    57: 'assets/images/category_icons/pant.svg',
    58: 'assets/images/category_icons/diamond.svg',
    59: 'assets/images/category_icons/watch.svg',
    60: 'assets/images/category_icons/lipstick.svg',
    61: 'assets/images/category_icons/tag.svg',
    62: 'assets/images/category_icons/gloves.svg',
    63: 'assets/images/category_icons/bikini.svg',
    
    //Education
    64: 'assets/images/category_icons/books.svg',
    65: 'assets/images/category_icons/briefcase.svg',
    66: 'assets/images/category_icons/pencils.svg',
    67: 'assets/images/category_icons/stapler.svg',
    68: 'assets/images/category_icons/protractor.svg',
    69: 'assets/images/category_icons/telescope.svg',
    70: 'assets/images/category_icons/globe.svg',
    71: 'assets/images/category_icons/microscope.svg',
    72: 'assets/images/category_icons/robot.svg',
    73: 'assets/images/category_icons/palette-and-brush.svg',
    74: 'assets/images/category_icons/flask.svg',
    75: 'assets/images/category_icons/plan.svg',

    //Electronics
    76: 'assets/images/category_icons/phone.svg',
    77: 'assets/images/category_icons/electronics.svg',
    78: 'assets/images/category_icons/computer.svg',
    79: 'assets/images/category_icons/laptop.svg',
    80: 'assets/images/category_icons/camera.svg',
    81: 'assets/images/category_icons/radio.svg',
    82: 'assets/images/category_icons/tv.svg',
    83: 'assets/images/category_icons/refrigerator.svg',
    84: 'assets/images/category_icons/washing-machine.svg',
    85: 'assets/images/category_icons/lamp.svg',

    //Persons
    86: 'assets/images/category_icons/man1.svg',
    87: 'assets/images/category_icons/man2.svg',
    88: 'assets/images/category_icons/man3.svg',
    89: 'assets/images/category_icons/man4.svg',
    90: 'assets/images/category_icons/woman1.svg',
    91: 'assets/images/category_icons/woman2.svg',
    92: 'assets/images/category_icons/woman3.svg',
    93: 'assets/images/category_icons/woman4.svg',
    94: 'assets/images/category_icons/baby1.svg',
    95: 'assets/images/category_icons/baby2.svg',
    96: 'assets/images/category_icons/baby3.svg',

    //Festival
    97: 'assets/images/category_icons/santa.svg',
    98: 'assets/images/category_icons/pumpkin.svg',
    99: 'assets/images/category_icons/fireworks.svg',
    100: 'assets/images/category_icons/snowman.svg',
    101: 'assets/images/category_icons/cake1.svg',
    102: 'assets/images/category_icons/candy.svg',

    //Sport
    103: 'assets/images/category_icons/bow-and-arrow.svg',
    104: 'assets/images/category_icons/golf.svg',
    105: 'assets/images/category_icons/swords.svg',
    106: 'assets/images/category_icons/boxing.svg',
    107: 'assets/images/category_icons/cricket.svg',
    108: 'assets/images/category_icons/table-tennis.svg',
    109: 'assets/images/category_icons/tennis-ball.svg',
    110: 'assets/images/category_icons/football.svg',
    111: 'assets/images/category_icons/rugby-ball.svg',
    112: 'assets/images/category_icons/dumbell.svg',
    113: 'assets/images/category_icons/treadmill.svg',
    114: 'assets/images/category_icons/swimming.svg',
    115: 'assets/images/category_icons/yoga.svg',

    //Transport
    116: 'assets/images/category_icons/car.svg',
    117: 'assets/images/category_icons/car1.svg',
    118: 'assets/images/category_icons/scooter.svg',
    119: 'assets/images/category_icons/train.svg',
    120: 'assets/images/category_icons/ship.svg',
    121: 'assets/images/category_icons/travel.svg',
    122: 'assets/images/category_icons/cycle.svg',
    123: 'assets/images/category_icons/bike.svg',

    //Health
    124: 'assets/images/category_icons/syringe.svg',
    125: 'assets/images/category_icons/pill.svg',
    126: 'assets/images/category_icons/tooth.svg',
    127: 'assets/images/category_icons/bandaids.svg',
    128: 'assets/images/category_icons/hospital.svg',
    129: 'assets/images/category_icons/health.svg',

    //Finance
    130: 'assets/images/category_icons/finance1.svg',
    131: 'assets/images/category_icons/credit-card.svg',
    132: 'assets/images/category_icons/money-plant.svg',
    133: 'assets/images/category_icons/clock-with-dollar-sign.svg',
    134: 'assets/images/category_icons/award.svg',
    135: 'assets/images/category_icons/other-income.svg',

    //Miscellaneous
    136: 'assets/images/category_icons/law.svg',
    137: 'assets/images/category_icons/law2.svg',
    138: 'assets/images/category_icons/paint.svg',
  };
}
