class CategoryIcons {
  static const iconData = {
    //General
    1: 'assets/images/category_icons/food.svg',
    2: 'assets/images/category_icons/phone.svg',
    3: 'assets/images/category_icons/house.svg',
    4: 'assets/images/category_icons/entertainment.svg',
    5: 'assets/images/category_icons/education.svg',
    6: 'assets/images/category_icons/beauty.svg',
    7: 'assets/images/category_icons/sport.svg',
    8: 'assets/images/category_icons/transportation.svg',
    9: 'assets/images/category_icons/clothing.svg',
    10: 'assets/images/category_icons/car.svg',
    11: 'assets/images/category_icons/electronics.svg',
    12: 'assets/images/category_icons/travel.svg',
    13: 'assets/images/category_icons/health.svg',
    14: 'assets/images/category_icons/pet.svg',
    15: 'assets/images/category_icons/carrot.svg',
    16: 'assets/images/category_icons/pear.svg',
    17: 'assets/images/category_icons/credit_card.svg',
    18: 'assets/images/category_icons/money_plant.svg',
    19: 'assets/images/category_icons/clock_with_dollar_sign.svg',
    20: 'assets/images/category_icons/award.svg',
    21: 'assets/images/category_icons/other_income.svg',
    22: 'assets/images/category_icons/electricity.svg',

    //Entertainment
    23: 'assets/images/category_icons/game_controller.svg',
    24: 'assets/images/category_icons/ghost.svg',
    25: 'assets/images/category_icons/tennis_ball.svg',
    26: 'assets/images/category_icons/table_tennis.svg',
    27: 'assets/images/category_icons/board_games.svg',
    28: 'assets/images/category_icons/radio.svg',
    29: 'assets/images/category_icons/robot.svg',
    30: 'assets/images/category_icons/nintendo.svg',
    31: 'assets/images/category_icons/water_gun.svg',
    32: 'assets/images/category_icons/bowling.svg',
    33: 'assets/images/category_icons/skate.svg',

    //Food
    34: 'assets/images/category_icons/bread.svg',
    35: 'assets/images/category_icons/tea.svg',
    36: 'assets/images/category_icons/food.svg',
    37: 'assets/images/category_icons/candy.svg',
    38: 'assets/images/category_icons/aubergine.svg',
    39: 'assets/images/category_icons/dog_food.svg',
    40: 'assets/images/category_icons/chicken_leg.svg',
    41: 'assets/images/category_icons/fish.svg',
    42: 'assets/images/category_icons/noodles.svg',
    43: 'assets/images/category_icons/pizza.svg',
    44: 'assets/images/category_icons/cake.svg',
    45: 'assets/images/category_icons/icecream.svg',
    46: 'assets/images/category_icons/milk.svg',
    47: 'assets/images/category_icons/watermelon.svg',
    48: 'assets/images/category_icons/strawberry.svg',
    49: 'assets/images/category_icons/pineapple.svg',
    50: 'assets/images/category_icons/beer.svg',
    
    //Apparel
    51: 'assets/images/category_icons/bag.svg',
    52: 'assets/images/category_icons/hat.svg',
    53: 'assets/images/category_icons/jewelry.svg',
    54: 'assets/images/category_icons/shoe.svg',
    55: 'assets/images/category_icons/perfume.svg',
    56: 'assets/images/category_icons/shirt.svg',
    57: 'assets/images/category_icons/pant.svg',
    58: 'assets/images/category_icons/diamond.svg',
    59: 'assets/images/category_icons/watch.svg',
    60: 'assets/images/category_icons/lipstick.svg',
    61: 'assets/images/category_icons/tag.svg',
    62: 'assets/images/category_icons/gloves.svg',
    63: 'assets/images/category_icons/bikini.svg',
    
    //Education
    64: 'assets/images/category_icons/books.svg',
    65: 'assets/images/category_icons/briefcase.svg',
    66: 'assets/images/category_icons/pencils.svg',
    67: 'assets/images/category_icons/stapler.svg',
    68: 'assets/images/category_icons/protractor.svg',
    69: 'assets/images/category_icons/telescope.svg',
    70: 'assets/images/category_icons/globe.svg',
    71: 'assets/images/category_icons/microscope.svg',
    72: 'assets/images/category_icons/robot.svg',
    73: 'assets/images/category_icons/palette_and_brush.svg',
    74: 'assets/images/category_icons/flask.svg',
    75: 'assets/images/category_icons/plan.svg',

    //Electronics
    76: 'assets/images/category_icons/phone.svg',
    77: 'assets/images/category_icons/electronics.svg',
    78: 'assets/images/category_icons/computer.svg',
    79: 'assets/images/category_icons/laptop.svg',
    80: 'assets/images/category_icons/camera.svg',
    81: 'assets/images/category_icons/radio.svg',
    82: 'assets/images/category_icons/tv.svg',
    83: 'assets/images/category_icons/refrigerator.svg',
    84: 'assets/images/category_icons/washing_machine.svg',
    85: 'assets/images/category_icons/lamp.svg',

    //Persons
    86: 'assets/images/category_icons/man1.svg',
    87: 'assets/images/category_icons/man2.svg',
    88: 'assets/images/category_icons/man3.svg',
    89: 'assets/images/category_icons/man4.svg',
    90: 'assets/images/category_icons/woman1.svg',
    91: 'assets/images/category_icons/woman2.svg',
    92: 'assets/images/category_icons/woman3.svg',
    93: 'assets/images/category_icons/woman4.svg',
    94: 'assets/images/category_icons/baby1.svg',
    95: 'assets/images/category_icons/baby2.svg',
    96: 'assets/images/category_icons/baby3.svg',

    //Festival
    97: 'assets/images/category_icons/santa.svg',
    98: 'assets/images/category_icons/pumpkin.svg',
    99: 'assets/images/category_icons/fireworks.svg',
    100: 'assets/images/category_icons/snowman.svg',
    101: 'assets/images/category_icons/cake1.svg',
    102: 'assets/images/category_icons/candy.svg',

    //Sport
    103: 'assets/images/category_icons/bow_and_arrow.svg',
    104: 'assets/images/category_icons/golf.svg',
    105: 'assets/images/category_icons/swords.svg',
    106: 'assets/images/category_icons/boxing.svg',
    107: 'assets/images/category_icons/cricket.svg',
    108: 'assets/images/category_icons/table_tennis.svg',
    109: 'assets/images/category_icons/tennis_ball.svg',
    110: 'assets/images/category_icons/football.svg',
    111: 'assets/images/category_icons/rugby_ball.svg',
    112: 'assets/images/category_icons/dumbell.svg',
    113: 'assets/images/category_icons/treadmill.svg',
    114: 'assets/images/category_icons/swimming.svg',
    115: 'assets/images/category_icons/yoga.svg',

    //Transport
    116: 'assets/images/category_icons/car.svg',
    117: 'assets/images/category_icons/car1.svg',
    118: 'assets/images/category_icons/scooter.svg',
    119: 'assets/images/category_icons/train.svg',
    120: 'assets/images/category_icons/ship.svg',
    121: 'assets/images/category_icons/travel.svg',
    122: 'assets/images/category_icons/cycle.svg',
    123: 'assets/images/category_icons/bike.svg',

    //Health
    124: 'assets/images/category_icons/syringe.svg',
    125: 'assets/images/category_icons/pill.svg',
    126: 'assets/images/category_icons/tooth.svg',
    127: 'assets/images/category_icons/bandaids.svg',
    128: 'assets/images/category_icons/hospital.svg',
    129: 'assets/images/category_icons/health.svg',

    //Finance
    130: 'assets/images/category_icons/finance1.svg',
    131: 'assets/images/category_icons/credit_card.svg',
    132: 'assets/images/category_icons/money_plant.svg',
    133: 'assets/images/category_icons/clock_with_dollar_sign.svg',
    134: 'assets/images/category_icons/award.svg',
    135: 'assets/images/category_icons/other_income.svg',

    //Miscellaneous
    136: 'assets/images/category_icons/law.svg',
    137: 'assets/images/category_icons/law2.svg',
    138: 'assets/images/category_icons/paint.svg',
  };

  static const notificationIconData = {
    //General
    1: 'resource://drawable/res_food',
    2: 'resource://drawable/res_phone',
    3: 'resource://drawable/res_house',
    4: 'resource://drawable/res_entertainment',
    5: 'resource://drawable/res_education',
    6: 'resource://drawable/res_beauty',
    7: 'resource://drawable/res_sport',
    8: 'resource://drawable/res_transportation',
    9: 'resource://drawable/res_clothing',
    10: 'resource://drawable/res_car',
    11: 'resource://drawable/res_electronics',
    12: 'resource://drawable/res_travel',
    13: 'resource://drawable/res_health',
    14: 'resource://drawable/res_pet',
    15: 'resource://drawable/res_carrot',
    16: 'resource://drawable/res_pear',
    17: 'resource://drawable/res_credit_card',
    18: 'resource://drawable/res_money_plant',
    19: 'resource://drawable/res_clock_with_dollar_sign',
    20: 'resource://drawable/res_award',
    21: 'resource://drawable/res_other_income',
    22: 'resource://drawable/res_electricity',

    //Entertainment
    23: 'resource://drawable/res_game_controller',
    24: 'resource://drawable/res_ghost',
    25: 'resource://drawable/res_tennis_ball',
    26: 'resource://drawable/res_table_tennis',
    27: 'resource://drawable/res_board_games',
    28: 'resource://drawable/res_radio',
    29: 'resource://drawable/res_robot',
    30: 'resource://drawable/res_nintendo',
    31: 'resource://drawable/res_water_gun',
    32: 'resource://drawable/res_bowling',
    33: 'resource://drawable/res_skate',

    //Food
    34: 'resource://drawable/res_bread',
    35: 'resource://drawable/res_tea',
    36: 'resource://drawable/res_food',
    37: 'resource://drawable/res_candy',
    38: 'resource://drawable/res_aubergine',
    39: 'resource://drawable/res_dog_food',
    40: 'resource://drawable/res_chicken_leg',
    41: 'resource://drawable/res_fish',
    42: 'resource://drawable/res_noodles',
    43: 'resource://drawable/res_pizza',
    44: 'resource://drawable/res_cake',
    45: 'resource://drawable/res_icecream',
    46: 'resource://drawable/res_milk',
    47: 'resource://drawable/res_watermelon',
    48: 'resource://drawable/res_strawberry',
    49: 'resource://drawable/res_pineapple',
    50: 'resource://drawable/res_beer',
    
    //Apparel
    51: 'resource://drawable/res_bag',
    52: 'resource://drawable/res_hat',
    53: 'resource://drawable/res_jewelry',
    54: 'resource://drawable/res_shoe',
    55: 'resource://drawable/res_perfume',
    56: 'resource://drawable/res_shirt',
    57: 'resource://drawable/res_pant',
    58: 'resource://drawable/res_diamond',
    59: 'resource://drawable/res_watch',
    60: 'resource://drawable/res_lipstick',
    61: 'resource://drawable/res_tag',
    62: 'resource://drawable/res_gloves',
    63: 'resource://drawable/res_bikini',
    
    //Education
    64: 'resource://drawable/res_books',
    65: 'resource://drawable/res_briefcase',
    66: 'resource://drawable/res_pencils',
    67: 'resource://drawable/res_stapler',
    68: 'resource://drawable/res_protractor',
    69: 'resource://drawable/res_telescope',
    70: 'resource://drawable/res_globe',
    71: 'resource://drawable/res_microscope',
    72: 'resource://drawable/res_robot',
    73: 'resource://drawable/res_palette_and_brush',
    74: 'resource://drawable/res_flask',
    75: 'resource://drawable/res_plan',

    //Electronics
    76: 'resource://drawable/res_phone',
    77: 'resource://drawable/res_electronics',
    78: 'resource://drawable/res_computer',
    79: 'resource://drawable/res_laptop',
    80: 'resource://drawable/res_camera',
    81: 'resource://drawable/res_radio',
    82: 'resource://drawable/res_tv',
    83: 'resource://drawable/res_refrigerator',
    84: 'resource://drawable/res_washing_machine',
    85: 'resource://drawable/res_lamp',

    //Persons
    86: 'resource://drawable/res_man1',
    87: 'resource://drawable/res_man2',
    88: 'resource://drawable/res_man3',
    89: 'resource://drawable/res_man4',
    90: 'resource://drawable/res_woman1',
    91: 'resource://drawable/res_woman2',
    92: 'resource://drawable/res_woman3',
    93: 'resource://drawable/res_woman4',
    94: 'resource://drawable/res_baby1',
    95: 'resource://drawable/res_baby2',
    96: 'resource://drawable/res_baby3',

    //Festival
    97: 'resource://drawable/res_santa',
    98: 'resource://drawable/res_pumpkin',
    99: 'resource://drawable/res_fireworks',
    100: 'resource://drawable/res_snowman',
    101: 'resource://drawable/res_cake1',
    102: 'resource://drawable/res_candy',

    //Sport
    103: 'resource://drawable/res_bow_and_arrow',
    104: 'resource://drawable/res_golf',
    105: 'resource://drawable/res_swords',
    106: 'resource://drawable/res_boxing',
    107: 'resource://drawable/res_cricket',
    108: 'resource://drawable/res_table_tennis',
    109: 'resource://drawable/res_tennis_ball',
    110: 'resource://drawable/res_football',
    111: 'resource://drawable/res_rugby_ball',
    112: 'resource://drawable/res_dumbell',
    113: 'resource://drawable/res_treadmill',
    114: 'resource://drawable/res_swimming',
    115: 'resource://drawable/res_yoga',

    //Transport
    116: 'resource://drawable/res_car',
    117: 'resource://drawable/res_car1',
    118: 'resource://drawable/res_scooter',
    119: 'resource://drawable/res_train',
    120: 'resource://drawable/res_ship',
    121: 'resource://drawable/res_travel',
    122: 'resource://drawable/res_cycle',
    123: 'resource://drawable/res_bike',

    //Health
    124: 'resource://drawable/res_syringe',
    125: 'resource://drawable/res_pill',
    126: 'resource://drawable/res_tooth',
    127: 'resource://drawable/res_bandaids',
    128: 'resource://drawable/res_hospital',
    129: 'resource://drawable/res_health',

    //Finance
    130: 'resource://drawable/res_finance1',
    131: 'resource://drawable/res_credit_card',
    132: 'resource://drawable/res_money_plant',
    133: 'resource://drawable/res_clock_with_dollar_sign',
    134: 'resource://drawable/res_award',
    135: 'resource://drawable/res_other_income',

    //Miscellaneous
    136: 'resource://drawable/res_law',
    137: 'resource://drawable/res_law2',
    138: 'resource://drawable/res_paint',
  };
}
